---
title: Cosario | Lo que venías buscando
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Cosario
description: Cosario te trae las cosas útiles e interesantes del internet. ¡Siempre
  contenidos de alta calidad y actualizados!
tags:
- blog
- template
- jekyll
- theme
- netlify
show_hero: false
menu:
- title: Inicio
  url: "/"
- title: About
  url: "/about"
- title: Contact
  url: "/contact"
- title: Feed
  url: "/feed.xml"
email: youremail@test.com
disqus_username: disqus_username
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: false
baseurl: ''
url: ''
google_analytics: UA-XXXXXXXX-X
language: en
categories_folder: category
sent_message_url: "/contact/message-sent/"
markdown: kramdown
highlighter: rouge
permalink: "/:title/"
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false
paginate_content:
  enabled: true
  debug: false
  collections:
  - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-paginate-content
- jekyll-remote-theme
exclude:
- package.json
- package-lock.json
- src
- node_modules
- initpost.sh
- Gemfile
- Gemfile.lock
- gulpfile.js
- README.md
version: v1.0.0
remote-theme: thiagorossener/jekflix-template